In [13]:
framecount =0

# First import the library
import pyrealsense2 as rs
# Import Numpy for easy array manipulation
import numpy as np
# Import OpenCV for easy image rendering
import cv2
# Import Pandas for save depth 
import pandas

# Create a pipeline
pipeline = rs.pipeline()

#Create a config and configure the pipeline to stream
#  different resolutions of color and depth streams
config = rs.config()
config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)
config.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 30)

# Start streaming
profile = pipeline.start(config)

# Getting the depth sensor's depth scale (see rs-align example for explanation)
depth_sensor = profile.get_device().first_depth_sensor()
depth_scale = depth_sensor.get_depth_scale()
print("Depth Scale is: " , depth_scale)

# We will be removing the background of objects more than
#  clipping_distance_in_meters meters away
clipping_distance_in_meters = 1 #1 meter
clipping_distance = clipping_distance_in_meters / depth_scale

# Create an align object
# rs.align allows us to perform alignment of depth frames to others frames
# The "align_to" is the stream type to which we plan to align depth frames.
align_to = rs.stream.color
align = rs.align(align_to)


# Streaming loop
try:
    while True:
        # Get frameset of color and depth
        frames = pipeline.wait_for_frames()
        # frames.get_depth_frame() is a 640x360 depth image

        # Align the depth frame to color frame
        aligned_frames = align.process(frames)

        # Get aligned frames
        aligned_depth_frame = aligned_frames.get_depth_frame() # aligned_depth_frame is a 640x480 depth image
        color_frame = aligned_frames.get_color_frame()

        # Validate that both frames are valid
        if not aligned_depth_frame or not color_frame:
            continue

        depth_image = np.asanyarray(aligned_depth_frame.get_data())
        color_image = np.asanyarray(color_frame.get_data())
        
        framecount = framecount+1
        print("Frame : ",framecount)
        print("Size : ",len(depth_image[0])," X ",len(depth_image))
        print(depth_image)
        print()

        # Remove background - Set pixels further than clipping_distance to grey
        grey_color = 153
        depth_image_3d = np.dstack((depth_image,depth_image,depth_image)) #depth image is 1 channel, color is 3 channels
        bg_removed = np.where((depth_image_3d > clipping_distance) | (depth_image_3d <= 0), grey_color, color_image)

        # Render images
        depth_colormap = cv2.applyColorMap(cv2.convertScaleAbs(depth_image, alpha=0.03), cv2.COLORMAP_JET)
        images = np.hstack((bg_removed, depth_colormap))
        cv2.namedWindow('Align Example', cv2.WINDOW_AUTOSIZE)
        cv2.imshow('Align Example', images)
        key = cv2.waitKey(1)
        # Press esc or 'q' to close the image window
        if key & 0xFF == ord('q') or key == 27:
            cv2.destroyAllWindows()
            break
finally:
    pipeline.stop()


Depth Scale is:  0.0010000000474974513
Frame :  1
Size :  640  X  480
[[   0    0    0 ... 1895 1895 1895]
 [   0    0    0 ... 1895 1895 1895]
 [   0    0    0 ... 1930 1930 1924]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  2
Size :  640  X  480
[[   0    0    0 ...    0    0 1712]
 [   0    0    0 ...    0 1671 1671]
 [   0    0    0 ... 1640 1640 1649]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  3
Size :  640  X  480
[[   0    0    0 ... 1756 1756 1761]
 [   0    0    0 ... 1756 1756 1761]
 [   0    0    0 ... 1776 1776 1781]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  4
Size :  640  X  480
[[   0    0    0 ... 1817 1812 1812]
 [   0    0    0 ... 1817 1812 1812]
 [   0    0    0 ...    0 1817 1817]
 ...
 [   0    0    0 ...    0    0    

Frame :  37
Size :  640  X  480
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Frame :  38
Size :  640  X  480
[[   0    0    0 ... 1817 1817 1823]
 [   0    0    0 ... 1817 1817 1823]
 [   0    0    0 ... 1828 1828 1828]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  39
Size :  640  X  480
[[   0    0    0 ...    0    0    0]
 [   0    0    0 ... 1966    0    0]
 [   0    0    0 ... 1930    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  40
Size :  640  X  480
[[   0    0    0 ... 1855 1855 1855]
 [   0    0    0 ... 1844 1850 1850]
 [   0    0    0 ... 1844 1844 1844]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  41
Size :  640  X  480
[[   0    0    0 ... 2030 2030 2

Frame :  74
Size :  640  X  480
[[   0    0    0 ... 1883 1883 1883]
 [   0    0    0 ... 1883 1883 1883]
 [   0    0    0 ... 1895 1895 1895]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  75
Size :  640  X  480
[[   0    0    0 ... 1796 1796 1796]
 [   0    0    0 ... 1796 1796 1796]
 [   0    0    0 ... 1796 1796 1801]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  76
Size :  640  X  480
[[   0    0    0 ... 1948 1948 1948]
 [   0    0    0 ... 1936 1942 1942]
 [   0    0    0 ... 1912 1912 1912]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  77
Size :  640  X  480
[[   0    0    0 ... 1791 1791 1791]
 [   0    0    0 ... 1791 1791 1791]
 [   0    0    0 ... 1791 1791 1791]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0  

Frame :  106
Size :  640  X  480
[[   0    0    0 ... 1866 1866 1866]
 [   0    0    0 ... 1861 1861 1861]
 [   0    0    0 ... 1850 1850 1850]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  107
Size :  640  X  480
[[   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0 1960]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  108
Size :  640  X  480
[[   0    0    0 ... 2037 2037 2037]
 [   0    0    0 ... 2017 2017 2017]
 [   0    0    0 ... 1991 1991 1991]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  109
Size :  640  X  480
[[   0    0    0 ... 1796 1796 1823]
 [   0    0    0 ... 1796 1796 1823]
 [   0    0    0 ... 1786 1786 1807]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0   

Size :  640  X  480
[[   0    0    0 ... 1906 1906 1906]
 [   0    0    0 ... 1906 1906 1906]
 [   0    0    0 ... 1900 1900 1900]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  141
Size :  640  X  480
[[   0    0    0 ... 1906 1906 1906]
 [   0    0    0 ... 1906 1906 1906]
 [   0    0    0 ... 1900 1900 1900]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  142
Size :  640  X  480
[[   0    0    0 ... 1906 1906 1906]
 [   0    0    0 ... 1883 1883 1883]
 [   0    0    0 ... 1861 1861 1861]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  143
Size :  640  X  480
[[   0    0    0 ... 1807 1801 1801]
 [   0    0    0 ... 1801 1796 1796]
 [   0    0    0 ... 1801 1796 1796]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [  

Frame :  172
Size :  640  X  480
[[   0    0    0 ... 1781 1781 1781]
 [   0    0    0 ... 1771 1771 1771]
 [   0    0    0 ... 1771 1771 1766]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  173
Size :  640  X  480
[[   0    0    0 ... 2135 2120 2120]
 [   0    0    0 ... 2127 2113 2113]
 [   0    0    0 ... 2120 2106 2106]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  174
Size :  640  X  480
[[   0    0    0 ... 2275 2250 2250]
 [   0    0    0 ... 2267 2242 2242]
 [   0    0    0 ... 2226 2202 2202]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  175
Size :  640  X  480
[[   0    0    0 ... 1855 1861 1861]
 [   0    0    0 ... 1855 1861 1861]
 [   0    0    0 ... 1850 1855 1855]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0   

Frame :  210
Size :  640  X  480
[[3871 3871 3871 ... 1844 1850 1844]
 [3896 3896 3896 ... 1844 1850 1844]
 [3945 3945 3945 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  211
Size :  640  X  480
[[3624 3624 3624 ... 2092 2092 2092]
 [3624 3645 3645 ... 2092 2092 2092]
 [3624 3645 3645 ... 2092 2099 2099]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  212
Size :  640  X  480
[[3824 3824 3801 ... 2142 2142    0]
 [3824 3824 3801 ... 2142 2127 2127]
 [3824 3824 3801 ... 2164 2127 2127]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  213
Size :  640  X  480
[[3801 3801 3801 ... 2030 2030 2030]
 [3778 3778 3778 ... 2030 2030 2030]
 [3778 3778 3778 ... 2037 2037 2037]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0   

Frame :  244
Size :  640  X  480
[[   0    0 3603 ... 1796 1796 1807]
 [   0    0 3562 ... 1796 1796 1807]
 [   0    0 3562 ... 1807 1807 1817]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  245
Size :  640  X  480
[[3603    0    0 ... 1883 1883 1883]
 [3603    0    0 ... 1877 1877 1877]
 [   0    0    0 ... 1872 1872 1872]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  246
Size :  640  X  480
[[   0    0    0 ... 1872 1872 1861]
 [   0    0    0 ... 1872 1872 1861]
 [   0    0    0 ... 1877 1877 1877]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  247
Size :  640  X  480
[[3645 3645 3645 ...    0    0    0]
 [3645 3645 3645 ...    0    0    0]
 [3667 3667 3645 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0   

Frame :  277
Size :  640  X  480
[[   0    0    0 ... 1985 1991 1991]
 [   0    0    0 ... 1972 1972 1972]
 [   0    0    0 ... 1960 1960 1960]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  278
Size :  640  X  480
[[   0    0    0 ... 1889 1906 1906]
 [   0    0    0 ... 1889 1900 1900]
 [   0    0    0 ... 1889 1895 1895]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  279
Size :  640  X  480
[[   0    0    0 ...    0    0    0]
 [   0    0    0 ... 1998 1998 1998]
 [   0    0    0 ... 1998 1998 1991]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  280
Size :  640  X  480
[[   0    0    0 ... 1912 1912 1906]
 [   0    0    0 ... 1912 1912 1906]
 [   0    0    0 ... 1948 1948 1948]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0   


Frame :  309
Size :  640  X  480
[[   0    0    0 ... 1924 1930 1930]
 [   0    0    0 ... 1924 1930 1930]
 [   0    0    0 ... 1942 1948 1948]
 ...
 [   0    0    0 ...    0    0    0]
 [ 686    0    0 ...    0    0    0]
 [ 685  685  685 ...    0    0    0]]

Frame :  310
Size :  640  X  480
[[   0    0    0 ... 2024 2024 2024]
 [   0    0    0 ... 2024 2024 2024]
 [   0    0    0 ... 2044 2044 2044]
 ...
 [   0    0    0 ...    0    0    0]
 [ 684  684  686 ...    0    0    0]
 [ 683  683  683 ...    0    0    0]]

Frame :  311
Size :  640  X  480
[[   0    0    0 ... 2017 2017 2017]
 [   0    0    0 ... 2017 2017 2017]
 [   0    0    0 ... 1991 1991 1991]
 ...
 [   0    0    0 ...    0    0    0]
 [ 682    0    0 ...    0    0    0]
 [ 681  682  682 ...    0    0    0]]

Frame :  312
Size :  640  X  480
[[   0    0    0 ... 1912 1912 1912]
 [   0    0    0 ... 1912 1912 1912]
 [   0    0    0 ... 1942 1942 1936]
 ...
 [   0    0    0 ...    0    0    0]
 [ 685  685  685 ...    0  

Frame :  342
Size :  640  X  480
[[65535 65535 65535 ...  1839  1839  1839]
 [65535 65535 65535 ...  1817  1823  1823]
 [65535 65535 65535 ...  1817  1812  1812]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]

Frame :  343
Size :  640  X  480
[[65535 65535 65535 ...  1924  1924  1924]
 [65535 65535 65535 ...  1924  1924  1924]
 [65535 65535 65535 ...  1942  1948  1948]
 ...
 [    0     0     0 ...     0     0     0]
 [  572   572   573 ...     0     0     0]
 [  572   572   573 ...     0     0     0]]

Frame :  344
Size :  640  X  480
[[    0     0 65535 ...  1930  1930  1930]
 [    0     0     0 ...  1900  1906  1906]
 [    0     0     0 ...  1866  1877  1877]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [  563     0     0 ...     0     0     0]]

Frame :  345
Size :  640  X  480
[[    0     0     0 ...  1791  1786  1786]
 [    0 65535 65535 ...  1791 

Frame :  375
Size :  640  X  480
[[65535 65535 65535 ...  1877  1877  1877]
 [65535 65535 65535 ...  1877  1877  1877]
 [65535 65535 65535 ...  1883  1883  1883]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]

Frame :  376
Size :  640  X  480
[[   0    0    0 ... 1877 1877 1877]
 [   0    0    0 ... 1877 1877 1877]
 [   0    0    0 ... 1912 1912 1900]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0  713  713 ...    0    0    0]]

Frame :  377
Size :  640  X  480
[[65535 65535 65535 ...  1667  1667  1676]
 [65535 65535 65535 ...  1667  1667  1676]
 [65535 65535 65535 ...  1667  1667  1680]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]

Frame :  378
Size :  640  X  480
[[65535 65535 65535 ...  1979  1979  1972]
 [65535 65535 65535 ...  1960  1960  1960]
 [65535 65535 65535 ...

Frame :  404
Size :  640  X  480
[[65535 65535 65535 ...  1936  1936  1936]
 [65535 65535 65535 ...  1936  1936  1936]
 [65535 65535 65535 ...  1972  1972  1972]
 ...
 [  715   714   714 ...     0     0     0]
 [  713   711   711 ...     0     0     0]
 [  711   707   707 ...     0     0     0]]

Frame :  405
Size :  640  X  480
[[65535 65535 65535 ...  1889  1889  1889]
 [65535 65535 65535 ...  1889  1889  1889]
 [65535 65535 65535 ...  1889  1889  1889]
 ...
 [  714   712   712 ...     0     0     0]
 [  712   709   709 ...     0     0     0]
 [  711   707   707 ...     0     0     0]]

Frame :  406
Size :  640  X  480
[[65535 65535 65535 ...  2099  2099  2099]
 [65535 65535 65535 ...  2092  2099  2099]
 [65535 65535 65535 ...  2092  2092  2099]
 ...
 [  717   716   714 ...     0     0     0]
 [  715   712   712 ...     0     0     0]
 [  714   711   711 ...     0     0     0]]

Frame :  407
Size :  640  X  480
[[    0 65535 65535 ...  1918  1918  1918]
 [    0 65535 65535 ...  1918 

Frame :  434
Size :  640  X  480
[[   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ... 1998 1998 1998]
 ...
 [ 700  699  699 ...    0    0    0]
 [ 700  697  697 ...    0    0    0]
 [ 700  696  696 ...    0    0    0]]

Frame :  435
Size :  640  X  480
[[65535 65535 65535 ...  1855  1855  1855]
 [65535 65535 65535 ...  1855  1855  1855]
 [65535 65535 65535 ...  1855  1855  1855]
 ...
 [  704   703   703 ...     0     0     0]
 [  704   703   703 ...     0     0     0]
 [  704   702   702 ...     0     0     0]]

Frame :  436
Size :  640  X  480
[[   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ... 1991 1991 1991]
 ...
 [ 703  701  701 ...    0    0    0]
 [ 703  700  700 ...    0    0    0]
 [ 701  699  699 ...    0    0    0]]

Frame :  437
Size :  640  X  480
[[   0    0    0 ... 1746 1741 1741]
 [   0    0    0 ... 1736 1736 1736]
 [   0    0    0 ... 1736 1736 1736]
 ...
 [ 703  701  701 ...    0    

Frame :  464
Size :  640  X  480
[[   0    0    0 ... 2044 2044 2037]
 [   0    0    0 ... 2044 2044 2037]
 [   0    0    0 ... 2064 2064 2057]
 ...
 [   0    0    0 ...    0    0    0]
 [ 700    0    0 ...    0    0    0]
 [ 693  691  691 ...    0    0    0]]

Frame :  465
Size :  640  X  480
[[   0    0    0 ... 1942 1942 1942]
 [   0    0    0 ... 1942 1942 1942]
 [   0    0    0 ... 1954 1954 1954]
 ...
 [ 695    0    0 ...    0    0    0]
 [ 691  688  688 ...    0    0    0]
 [ 689  686  686 ...    0    0    0]]

Frame :  466
Size :  640  X  480
[[   0    0    0 ... 1861 1861 1861]
 [   0    0    0 ... 1861 1861 1861]
 [   0    0    0 ... 1883 1883 1883]
 ...
 [ 696    0    0 ...    0    0    0]
 [ 691  689  689 ...    0    0    0]
 [ 689  687  687 ...    0    0    0]]

Frame :  467
Size :  640  X  480
[[   0    0    0 ... 2064 2064    0]
 [   0    0    0 ... 2064 2064 2106]
 [   0    0    0 ... 2120 2106 2106]
 ...
 [   0    0    0 ...    0    0    0]
 [ 689  687  687 ...    0   

Frame :  496
Size :  640  X  480
[[   0    0    0 ... 1751 1746 1746]
 [   0    0    0 ... 1746 1746 1746]
 [   0    0    0 ... 1746 1746 1746]
 ...
 [   0    0    0 ...    0    0    0]
 [ 703  701  701 ...    0    0    0]
 [ 700  699  699 ...    0    0    0]]

Frame :  497
Size :  640  X  480
[[   0    0    0 ...    0    0 1877]
 [   0    0    0 ...    0    0 1877]
 [   0    0    0 ... 1877 1877 1877]
 ...
 [   0    0    0 ...    0    0    0]
 [ 701  697  697 ...    0    0    0]
 [ 699  694  694 ...    0    0    0]]

Frame :  498
Size :  640  X  480
[[   0    0    0 ... 1930 1942 1942]
 [   0    0    0 ... 1930 1942 1942]
 [   0    0    0 ... 1936 1948 1948]
 ...
 [   0    0    0 ...    0    0    0]
 [ 704  700  700 ...    0    0    0]
 [ 700  700  700 ...    0    0    0]]

Frame :  499
Size :  640  X  480
[[   0    0    0 ... 1861 1861 1861]
 [   0    0    0 ... 1855 1855 1855]
 [   0    0    0 ... 1850 1850 1850]
 ...
 [   0    0    0 ...    0    0    0]
 [ 701  699  699 ...    0   

Frame :  531
Size :  640  X  480
[[   0    0    0 ... 2004    0    0]
 [   0    0    0 ... 2004    0    0]
 [   0    0    0 ... 2017    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  532
Size :  640  X  480
[[   0    0    0 ... 1807 1807 1812]
 [   0    0    0 ... 1807 1807 1812]
 [   0    0    0 ... 1817 1823 1823]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  533
Size :  640  X  480
[[   0    0    0 ... 1850 1850 1850]
 [   0    0    0 ... 1850 1850 1850]
 [   0    0    0 ... 1855 1855 1855]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [ 685  685  683 ...    0    0    0]]

Frame :  534
Size :  640  X  480
[[   0    0    0 ... 2135 2135 2135]
 [   0    0    0 ... 2135 2135 2135]
 [   0    0    0 ... 2135 2135 2135]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0   

Frame :  566
Size :  640  X  480
[[   0    0    0 ... 1924 1924 1924]
 [   0    0    0 ... 1924 1924 1924]
 [   0    0    0 ... 1942 1948 1948]
 ...
 [   0    0    0 ...    0    0    0]
 [ 684  684  682 ...    0    0    0]
 [ 684  684  681 ...    0    0    0]]

Frame :  567
Size :  640  X  480
[[   0    0    0 ... 1839 1844 1844]
 [   0    0    0 ... 1839 1844 1844]
 [   0    0    0 ... 1850 1855 1855]
 ...
 [   0    0    0 ...    0    0    0]
 [ 684  684  681 ...    0    0    0]
 [ 684  684  680 ...    0    0    0]]

Frame :  568
Size :  640  X  480
[[   0    0    0 ... 1844 1844 1844]
 [   0    0    0 ... 1844 1844 1844]
 [   0    0    0 ... 1844 1844 1844]
 ...
 [ 682  682  681 ...    0    0    0]
 [ 682  682  681 ...    0    0    0]
 [ 683    0  681 ...    0    0    0]]

Frame :  569
Size :  640  X  480
[[   0    0    0 ... 1889 1889 1889]
 [   0    0    0 ... 1889 1889 1889]
 [   0    0    0 ... 1912 1912 1912]
 ...
 [ 686  686    0 ...    0    0    0]
 [ 686  685  685 ...    0   

Frame :  601
Size :  640  X  480
[[   0    0    0 ... 1866    0    0]
 [   0    0    0 ... 1866 1895 1895]
 [   0    0    0 ... 1895 1895 1895]
 ...
 [ 657    0    0 ...    0    0    0]
 [ 657  657  657 ...    0    0    0]
 [ 656  656  656 ...    0    0    0]]

Frame :  602
Size :  640  X  480
[[   0    0    0 ... 1900 1900 1900]
 [   0    0    0 ... 1900 1900 1900]
 [   0    0    0 ... 1912 1912 1912]
 ...
 [ 654  653  653 ...    0    0    0]
 [ 653  653  653 ...    0    0    0]
 [ 653  653  653 ...    0    0    0]]

Frame :  603
Size :  640  X  480
[[   0    0    0 ... 1828 1833 1833]
 [   0    0    0 ... 1828 1833 1833]
 [   0    0    0 ... 1855 1866 1866]
 ...
 [ 652  652  653 ...    0    0    0]
 [ 652  652  653 ...    0    0    0]
 [ 652  652  653 ...    0    0    0]]

Frame :  604
Size :  640  X  480
[[   0    0    0 ... 1866 1866 1866]
 [   0    0    0 ... 1866 1866 1866]
 [   0    0    0 ... 1866 1866 1866]
 ...
 [ 655  655  655 ...    0    0    0]
 [ 654  654  655 ...    0   

Frame :  637
Size :  640  X  480
[[65535 65535 65535 ...  1823  1823  1823]
 [65535 65535 65535 ...  1823  1823  1823]
 [65535 65535 65535 ...  1833  1833  1833]
 ...
 [  654   654   655 ...     0     0     0]
 [  654   654   654 ...     0     0     0]
 [  654   654   654 ...     0     0     0]]

Frame :  638
Size :  640  X  480
[[   0    0    0 ... 1960 1960 1960]
 [   0    0    0 ... 1960 1960 1960]
 [   0    0    0 ... 1972 1972 1972]
 ...
 [ 657    0    0 ...    0    0    0]
 [ 657    0    0 ...    0    0    0]
 [ 657    0    0 ...    0    0    0]]

Frame :  639
Size :  640  X  480
[[    0     0 65535 ...  1833  1844  1844]
 [65535 65535 65535 ...  1823  1833  1833]
 [65535 65535 65535 ...  1817  1828  1828]
 ...
 [  660     0     0 ...     0     0     0]
 [  659   659   659 ...     0     0     0]
 [  657   659   659 ...     0     0     0]]

Frame :  640
Size :  640  X  480
[[65535 65535 65535 ...  2017  2017  2017]
 [65535 65535 65535 ...  2004  2004  2004]
 [65535 65535 65535 ...

Frame :  669
Size :  640  X  480
[[   0    0    0 ... 2024 2024 2024]
 [   0    0    0 ... 2024 2024 2024]
 [   0    0    0 ... 2011 2011 2011]
 ...
 [   0    0    0 ...    0    0    0]
 [ 675    0    0 ...    0    0    0]
 [ 673  673  673 ...    0    0    0]]

Frame :  670
Size :  640  X  480
[[   0    0    0 ... 1872 1883 1883]
 [   0    0    0 ... 1872 1883 1883]
 [   0    0    0 ... 1866 1883 1883]
 ...
 [ 672  672  672 ...    0    0    0]
 [ 672  672  672 ...    0    0    0]
 [ 672    0    0 ...    0    0    0]]

Frame :  671
Size :  640  X  480
[[   0    0    0 ... 1866 1866 1866]
 [   0    0    0 ... 1866 1866 1866]
 [   0    0    0 ... 1866 1872 1872]
 ...
 [ 671  671  671 ...    0    0    0]
 [ 671  671  671 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  672
Size :  640  X  480
[[   0    0    0 ... 1900 1900 1900]
 [   0    0    0 ... 1889 1889 1889]
 [   0    0    0 ... 1883 1883 1883]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0   

Frame :  703
Size :  640  X  480
[[    0     0     0 ...  1833  1833  1833]
 [    0     0 65535 ...  1833  1833  1833]
 [    0     0 65535 ...  1833  1833  1833]
 ...
 [  661     0     0 ...     0     0     0]
 [  661     0     0 ...     0     0     0]
 [  662     0     0 ...     0     0     0]]

Frame :  704
Size :  640  X  480
[[   0    0    0 ... 1776 1776 1781]
 [   0    0    0 ... 1776 1776 1781]
 [   0    0    0 ... 1781 1781 1786]
 ...
 [   0    0    0 ...    0    0    0]
 [ 663    0    0 ...    0    0    0]
 [ 662  662  662 ...    0    0    0]]

Frame :  705
Size :  640  X  480
[[   0    0    0 ... 1998 1998 1998]
 [   0    0    0 ... 1998 1998 1998]
 [   0    0    0 ... 1998 1998 1998]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [ 665    0    0 ...    0    0    0]]

Frame :  706
Size :  640  X  480
[[   0    0    0 ... 1972 1972 1972]
 [   0    0    0 ... 1972 1972 1972]
 [   0    0    0 ... 1972 1972 1972]
 ...
 [   0    0    0 ...    0    

Frame :  734
Size :  640  X  480
[[   0    0    0 ... 1985 1985 1979]
 [   0    0    0 ... 1960 1960 1960]
 [   0    0    0 ... 1942 1942 1942]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  735
Size :  640  X  480
[[   0    0    0 ...    0 1796 1796]
 [   0    0    0 ...    0 1796 1796]
 [   0    0    0 ... 1850 1850 1850]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  736
Size :  640  X  480
[[    0     0     0 ...  2078  2078     0]
 [    0 65535 65535 ...  2078  2078     0]
 [    0 65535 65535 ...  2085     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]

Frame :  737
Size :  640  X  480
[[   0    0    0 ... 1828 1828 1823]
 [   0    0    0 ... 1828 1828 1823]
 [   0    0    0 ... 1833 1833 1833]
 ...
 [ 599    0    0 ...    0    

Frame :  767
Size :  640  X  480
[[65535 65535 65535 ...  2113     0     0]
 [    0     0 65535 ...  2106  2092  2092]
 [    0     0 65535 ...  2092  2085  2085]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]

Frame :  768
Size :  640  X  480
[[   0    0    0 ... 1823 1812 1812]
 [   0    0    0 ... 1823 1812 1812]
 [   0    0    0 ... 1833 1833 1833]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  769
Size :  640  X  480
[[   0    0    0 ... 1807 1796 1796]
 [   0    0    0 ... 1807 1796 1796]
 [   0    0    0 ... 1828 1817 1817]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  770
Size :  640  X  480
[[   0    0    0 ... 1850 1850 1850]
 [   0    0    0 ... 1844 1850 1850]
 [   0    0    0 ... 1839 1844 1844]
 ...
 [   0  586  586 ...    0    

Size :  640  X  480
[[    0 65535 65535 ...  1906  1906  1906]
 [    0 65535 65535 ...  1906  1906  1906]
 [    0 65535 65535 ...  1924  1924  1924]
 ...
 [  571   571   572 ...     0     0     0]
 [  571   571   572 ...     0     0     0]
 [  571   571   571 ...     0     0     0]]

Frame :  800
Size :  640  X  480
[[   0    0    0 ... 1861 1872 1872]
 [   0    0    0 ... 1861 1872 1872]
 [   0    0    0 ... 1866 1877 1877]
 ...
 [ 571  571  572 ...    0    0    0]
 [ 571  571  572 ...    0    0    0]
 [   0  573  573 ...    0    0    0]]

Frame :  801
Size :  640  X  480
[[   0    0    0 ... 2017    0    0]
 [   0    0    0 ... 2017    0    0]
 [   0    0    0 ... 1954    0    0]
 ...
 [ 573  573  574 ...    0    0    0]
 [ 573  573  573 ...    0    0    0]
 [ 573  573  573 ...    0    0    0]]

Frame :  802
Size :  640  X  480
[[    0 65535 65535 ...  1828  1828  1828]
 [65535 65535 65535 ...  1828  1828  1828]
 [65535 65535 65535 ...  1828  1828  1828]
 ...
 [  571   571   573 ... 

Frame :  832
Size :  640  X  480
[[   0    0    0 ...    0    0    0]
 [   0    0    0 ... 1877    0    0]
 [   0    0    0 ... 1877    0    0]
 ...
 [ 574  573  573 ...    0    0    0]
 [ 573  572  572 ...    0    0    0]
 [ 572  572  572 ...    0    0    0]]

Frame :  833
Size :  640  X  480
[[   0    0    0 ... 2017 2030 2030]
 [   0    0    0 ... 2017 2024 2017]
 [   0    0    0 ... 2017 2024 2017]
 ...
 [   0  572  572 ...    0    0    0]
 [ 571  571  571 ...    0    0    0]
 [ 570  570  570 ...    0    0    0]]

Frame :  834
Size :  640  X  480
[[    0 65535 65535 ...  2011  2011  2004]
 [    0 65535 65535 ...  1998  1998  1991]
 [    0 65535 65535 ...  1991  1991  1991]
 ...
 [  573   573   573 ...     0     0     0]
 [  573   573   573 ...     0     0     0]
 [  571   571   571 ...     0     0     0]]

Frame :  835
Size :  640  X  480
[[65535 65535 65535 ...  1895  1895  1895]
 [65535 65535 65535 ...  1877  1877  1877]
 [65535 65535 65535 ...  1861  1861  1861]
 ...
 [    0   5

Frame :  864
Size :  640  X  480
[[   0    0    0 ... 1833 1839 1839]
 [   0    0    0 ... 1833 1839 1839]
 [   0    0    0 ... 1839 1839 1839]
 ...
 [   0    0    0 ...    0    0    0]
 [ 685  685  685 ...    0    0    0]
 [ 684  684  683 ...    0    0    0]]

Frame :  865
Size :  640  X  480
[[65535 65535 65535 ...  1866  1866  1866]
 [65535 65535 65535 ...  1866  1866  1866]
 [65535 65535 65535 ...  1877  1883  1883]
 ...
 [    0     0     0 ...     0     0     0]
 [  683   683   683 ...     0     0     0]
 [  683   683   682 ...     0     0     0]]

Frame :  866
Size :  640  X  480
[[    0 65535 65535 ...  1966  1966  1960]
 [    0 65535 65535 ...  1966  1966  1960]
 [    0 65535 65535 ...  1966  1966  1966]
 ...
 [    0     0     0 ...     0     0     0]
 [  686   685   685 ...     0     0     0]
 [  686   685   685 ...     0     0     0]]

Frame :  867
Size :  640  X  480
[[    0 65535 65535 ...  1801  1801  1801]
 [    0 65535 65535 ...  1801  1801  1801]
 [    0 65535 65535 ...

Frame :  893
Size :  640  X  480
[[65535 65535 65535 ...  1844  1844  1844]
 [65535 65535 65535 ...  1844  1844  1844]
 [65535 65535 65535 ...  1844  1844  1844]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]

Frame :  894
Size :  640  X  480
[[   0    0    0 ... 1889 1889 1889]
 [   0    0    0 ... 1889 1889 1889]
 [   0    0    0 ... 1889 1889 1889]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [ 678  678  678 ...    0    0    0]]

Frame :  895
Size :  640  X  480
[[   0    0    0 ...    0 1801 1801]
 [   0    0    0 ...    0 1801 1801]
 [   0    0    0 ... 1833    0 1817]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  896
Size :  640  X  480
[[65535 65535 65535 ...  2044  2044  2037]
 [65535 65535 65535 ...  2044  2044  2037]
 [65535 65535 65535 ...  2050  2050  2044]
 ...
 [    0    

Frame :  923
Size :  640  X  480
[[   0    0    0 ...    0    0    0]
 [   0    0    0 ... 2057 2057 2057]
 [   0    0    0 ... 2057 2057 2057]
 ...
 [ 563  563    0 ...    0    0    0]
 [ 563  563    0 ...    0    0    0]
 [ 562  563  563 ...    0    0    0]]

Frame :  924
Size :  640  X  480
[[   0    0    0 ... 1912 1912 1912]
 [   0    0    0 ... 1912 1912 1912]
 [   0    0    0 ... 1924 1924 1924]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  925
Size :  640  X  480
[[65535 65535 65535 ...  1889  1889  1889]
 [65535 65535 65535 ...  1889  1889  1889]
 [    0 65535 65535 ...  1912  1918  1918]
 ...
 [    0   561   561 ...     0     0     0]
 [    0   560   560 ...     0     0     0]
 [  560   560   560 ...     0     0     0]]

Frame :  926
Size :  640  X  480
[[   0    0    0 ... 1991 1991 1991]
 [   0    0    0 ... 1985 1985 1985]
 [   0    0    0 ... 1985 1985 1985]
 ...
 [ 561  561  561 ...    0    

Frame :  957
Size :  640  X  480
[[   0    0    0 ... 1855 1855 1855]
 [   0    0    0 ... 1855 1855 1855]
 [   0    0    0 ... 1866 1866 1861]
 ...
 [ 556  555  555 ...    0    0    0]
 [ 555  554  554 ...    0    0    0]
 [ 554  554  554 ...    0    0    0]]

Frame :  958
Size :  640  X  480
[[   0    0    0 ... 1912 1918 1918]
 [   0    0    0 ... 1900 1900 1900]
 [   0    0    0 ... 1895 1895 1895]
 ...
 [ 557  556  556 ...    0    0    0]
 [ 556  555  555 ...    0    0    0]
 [ 556  555  555 ...    0    0    0]]

Frame :  959
Size :  640  X  480
[[   0    0    0 ... 1883 1883 1883]
 [   0    0    0 ... 1883 1883 1883]
 [   0    0    0 ... 1895 1900 1900]
 ...
 [   0  556  556 ...    0    0    0]
 [   0  556  556 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  960
Size :  640  X  480
[[   0    0    0 ... 1972 1979 1979]
 [   0    0    0 ... 1972 1979 1979]
 [   0    0    0 ... 1960 1966 1966]
 ...
 [ 558  557  557 ...    0    0    0]
 [ 558  556  556 ...    0   

 [   0    0    0 ...    0    0    0]]

Frame :  990
Size :  640  X  480
[[   0    0    0 ...    0    0    0]
 [   0    0    0 ... 2064    0    0]
 [   0    0    0 ... 2037    0    0]
 ...
 [ 557  556  556 ...    0    0    0]
 [ 557  556  556 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  991
Size :  640  X  480
[[   0    0    0 ... 1883 1883 1883]
 [   0    0    0 ... 1866 1883 1883]
 [   0    0    0 ... 1855    0    0]
 ...
 [ 557  556  556 ...    0    0    0]
 [ 557  556  556 ...    0    0    0]
 [ 557  557    0 ...    0    0    0]]

Frame :  992
Size :  640  X  480
[[   0    0    0 ... 1912 1912 1912]
 [   0    0    0 ... 1906 1906 1906]
 [   0    0    0 ... 1889 1889 1889]
 ...
 [ 556  556  556 ...    0    0    0]
 [ 556  556  556 ...    0    0    0]
 [ 558  557  557 ...    0    0    0]]

Frame :  993
Size :  640  X  480
[[   0    0    0 ... 1889 1889 1877]
 [   0    0    0 ... 1889 1889 1877]
 [   0    0    0 ... 1912 1912 1895]
 ...
 [ 558  558  558 ...    0 

Frame :  1024
Size :  640  X  480
[[   0    0    0 ... 1833 1844 1844]
 [   0    0    0 ... 1833 1844 1844]
 [   0    0    0 ... 1844 1850 1850]
 ...
 [   0    0    0 ...    0    0    0]
 [ 554  554  554 ...    0    0    0]
 [ 553  553  553 ...    0    0    0]]

Frame :  1025
Size :  640  X  480
[[   0    0    0 ... 2057    0    0]
 [   0    0    0 ... 2044 2044 2044]
 [   0    0    0 ... 2037 2037 2030]
 ...
 [   0    0    0 ...    0    0    0]
 [ 556  556    0 ...    0    0    0]
 [ 556  556  556 ...    0    0    0]]

Frame :  1026
Size :  640  X  480
[[   0    0    0 ... 1761 1761 1766]
 [   0    0    0 ... 1761 1761 1766]
 [   0    0    0 ... 1776 1776 1786]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [ 556  556    0 ...    0    0    0]]

Frame :  1027
Size :  640  X  480
[[   0    0    0 ... 1817 1817 1823]
 [   0    0    0 ... 1817 1817 1823]
 [   0    0    0 ... 1833 1844 1844]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    

Frame :  1056
Size :  640  X  480
[[65535 65535     0 ...  1895  1895  1895]
 [65535 65535 65535 ...  1895  1895  1895]
 [65535 65535 65535 ...  1906  1906  1906]
 ...
 [    0   567   567 ...     0     0     0]
 [  568   567   567 ...     0     0     0]
 [  568   568   569 ...     0     0     0]]

Frame :  1057
Size :  640  X  480
[[   0    0    0 ...    0    0 1948]
 [   0    0    0 ...    0    0 1948]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [ 565    0    0 ...    0    0    0]
 [ 564  564  564 ...    0    0    0]]

Frame :  1058
Size :  640  X  480
[[   0    0    0 ... 1966 1966 1960]
 [   0    0    0 ... 1966 1966 1960]
 [   0    0    0 ... 1966 1966 1966]
 ...
 [ 572  571  571 ...    0    0    0]
 [ 571  570  570 ...    0    0    0]
 [ 570  570  570 ...    0    0    0]]

Frame :  1059
Size :  640  X  480
[[   0    0    0 ... 1828 1833 1833]
 [   0    0    0 ... 1828 1833 1833]
 [   0    0    0 ... 1828 1839 1839]
 ...
 [   0    0    0 ...    0

Size :  640  X  480
[[    0     0 65535 ...  1924  1930  1930]
 [    0 65535 65535 ...  1918  1924  1924]
 [    0 65535 65535 ...  1912  1912  1912]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]

Frame :  1088
Size :  640  X  480
[[    0     0 65535 ...  1900  1900  1900]
 [    0     0 65535 ...  1900  1900  1900]
 [    0     0 65535 ...  2030  2030  1966]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]

Frame :  1089
Size :  640  X  480
[[   0    0    0 ... 1991 1991 1991]
 [   0    0    0 ... 1966 1979 1979]
 [   0    0    0 ... 1948 1960 1960]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  1090
Size :  640  X  480
[[   0    0    0 ... 1985 1985 1985]
 [   0    0    0 ... 1966 1972 1972]
 [   0    0    0 ... 1954 1960 1960]
 ...
 [ 

Frame :  1119
Size :  640  X  480
[[   0    0    0 ... 1930 1930 1930]
 [   0    0    0 ... 1912 1912 1912]
 [   0    0    0 ... 1895 1900 1900]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  1120
Size :  640  X  480
[[   0    0    0 ... 2050    0    0]
 [   0    0    0 ... 2050 2071 2071]
 [   0    0    0 ... 2064 2071 2071]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

Frame :  1121
Size :  640  X  480
[[   0    0    0 ... 1877 1877 1877]
 [   0    0    0 ... 1872 1872 1872]
 [   0    0    0 ... 1872 1872 1872]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [ 536    0    0 ...    0    0    0]]

Frame :  1122
Size :  640  X  480
[[   0    0    0 ... 1979 1979 1979]
 [   0    0    0 ... 1979 1979 1979]
 [   0    0    0 ... 1998 1998 1998]
 ...
 [ 535  535  535 ...    0    0    0]
 [ 535  535  535 ...    

Frame :  1154
Size :  640  X  480
[[ 721  721  721 ... 1889 1889 1889]
 [ 721  721  721 ... 1883 1883 1883]
 [ 721  721  721 ... 1883 1883 1883]
 ...
 [   0    0    0 ...    0    0    0]
 [ 687  688  689 ...    0    0    0]
 [ 687  688  689 ...    0    0    0]]

Frame :  1155
Size :  640  X  480
[[ 720  720  720 ... 1872 1877 1877]
 [ 720  720  720 ... 1872 1877 1877]
 [ 720  720  721 ... 1872 1877 1877]
 ...
 [ 684    0    0 ...    0    0    0]
 [ 684  684    0 ...    0    0    0]
 [ 684  684  685 ...    0    0    0]]

Frame :  1156
Size :  640  X  480
[[ 718  718  718 ...    0    0    0]
 [ 718  718  718 ...    0    0 1966]
 [ 718  718  718 ... 1942 1942 1942]
 ...
 [   0    0    0 ...    0    0    0]
 [ 680  680  680 ...    0    0    0]
 [ 680  680  680 ...    0    0    0]]

Frame :  1157
Size :  640  X  480
[[ 717  717  717 ...    0    0    0]
 [ 717  717  717 ...    0    0    0]
 [ 717  717  718 ... 2085 2064 2064]
 ...
 [ 686    0    0 ...    0    0    0]
 [ 686  686  686 ...    